# Dependencies

# Permalinks
permalink:        pretty

# Setup
title:            Brooke Ballagh
tagline:          'A Collection of my Journalism Work'
description:      I am a student at the University of Iowa studying Journalism & Mass Communication with the goal of becoming a Television News Broadcast Producer.
url:              http://bballagh.github.io
baseurl:          /profile-hyde/
shortbaseurl:     /profile-hyde
colorscheme:      ''
#options '' (black), theme-base-08 (red), theme-base-09 (orange), theme-base-0a (yellow), theme-base-0b (green), theme-base-0c (cyan), theme-base-0d (blue), theme-base-0e (magenta), theme-base-0f (brown)


author:
  name:           'Brooke Ballagh'
  url:            ''
  
paginate:         5

# Custom vars
version:          0.8.1

